

server:
  port: 9002


#DB Configuration:
spring:
  profiles: dev
  application:
    name: product-service #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_jingdong?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root



mybatis:
  type-aliases-package: com.wanshi.po
  mapper-locations: classpath:mapper/*Mapper.xml

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #defaultZone: http://localhost:6001/eureka
      defaultZone: http://127.0.0.1:6868/eureka
---
server:
  port: 9003


#DB Configuration:
spring:
  profiles: prod
  application:
    name: product-service #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_jingdong2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root



mybatis:
  type-aliases-package: com.wanshi.po
  mapper-locations: classpath:mapper/*Mapper.xml

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #defaultZone: http://localhost:6001/eureka
      defaultZone: http://127.0.0.1:6868/eureka



