

server:
  port: 8000


#DB Configuration:
spring:
  profiles: dev
  application:
    name: order-service #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_jingdong?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


#spring\u96C6\u6210Mybatis\u73AF\u5883
#pojo\u522B\u540D\u626B\u63CF\u5305
mybatis:
  type-aliases-package: com.wanshi.po
#\u52A0\u8F7DMybatis\u6620\u5C04\u6587\u4EF6
  mapper-locations: classpath:mapper/*Mapper.xml

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #defaultZone: http://localhost:6001/eureka
      defaultZone: http://127.0.0.1:6868/eureka




feign:
  hystrix:
    enabled: true
    
---



server:
  port: 8000


#DB Configuration:
spring:
  profiles: prod
  application:
    name: order-service #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_jingdong?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


#spring\u96C6\u6210Mybatis\u73AF\u5883
#pojo\u522B\u540D\u626B\u63CF\u5305
mybatis:
  type-aliases-package: com.wanshi.po
#\u52A0\u8F7DMybatis\u6620\u5C04\u6587\u4EF6
  mapper-locations: classpath:mapper/*Mapper.xml

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #defaultZone: http://localhost:6001/eureka
      defaultZone: http://127.0.0.1:6868/eureka




feign:
  hystrix:
    enabled: true

